### PR TITLE
Adds the ability to pass in custom colors

### PR DESCRIPTION
**Pull request by phantomxc**
This is going to be breaking changes to the way the library is utilized. With the need to compile on the fly values for the core and client colors, the original design will not suffice. 

Instead of importing the light / dark themes, you'll import the buildTheme function and pass in your desired theme and custom colors to get your object/JSON.

### CODE REVIEW

**Comment by brianrclay** [comment]
@jgerlach Do you want to merge this when ready?

**Comment by brianrclay** [comment]
@phantomxc Is there a new build process associated with this? Right now we have to do npm run build... etc. Is there a new build process?

**Comment by phantomxc** [comment]
I'll update the documentation when this is closer to being ready. I spoke with Denna and we will need a ruby script to compile the JSON assets as they don't have a JS env for their build process and I wouldn't ask them to introduce that just for this.

**Comment by phantomxc** [comment]
Also, don't let this stop you from updating the colors on the dark theme. I'll deal with any conflicts that may arise.

**Comment by benschinn** [comment]
@phantomxc have you already written the ruby script for compiling the JSON assets? I'd be happy to take it on if it still needs to be done. 

I'd be interested in maybe writing it in Go so that if someone who doesn't have ruby or JS env set up can just run the binary.

**Comment by phantomxc** [comment]
I'm going to chat with the mobile team today and see if node can live on their build server. I would prefer to keep this a single simple script.

**Comment by phantomxc** [comment]
I think this is ready for another look. @jgerlach @brianrclay

**Comment by brianrclay** [comment]
@phantomxc did you talk with mobile to see if they can support node?

**Comment by phantomxc** [comment]
@brianrclay 
>Sounds good. When the time comes we’ll have nodejs and npm available

Sheldon

**Comment by brianrclay** [comment]
Awesome. Just need @jgerlach to give the sign off on the change. I am unsure how this will affect his current work in the client portal.

**Pull request merged**
