### PR TITLE
Changes to Brand100-Brand500 from Primary*

### PR DESCRIPTION
**Pull request by phantomxc**
Updates to support the idea of having primary colors and brand colors.

### CODE REVIEW

**Comment by DrewWarrenTIY** [comment]
Are there any concerns for changing from `Primary` to `Brand` and still respecting current configs which seem to use the `Primary` string?

**Comment by phantomxc** [comment]
That's why this is 8.0.0. It's a breaking change.

**Comment by DrewWarrenTIY** [comment]
:shipit: 

Removes Primary, Replaces with Brand. Looks good to me. 

We should announce at least internally that 8.0 will need to be done in parallel with updating "Primary" to "Brand" in repos where it is used.

**Comment by phantomxc** [comment]
We've got to update Kyper before it even makes it internal.

**Pull request merged**
