### PR TITLE
Update token generation scripts

### PR DESCRIPTION
**Pull request by run-time**
This consolidates the process for turning the raw mx-design-tokens into the following file formats...

| Command              | Description                                                                 |
| -------------------- | --------------------------------------------------------------------------- |
| `npm run build:docs` | Update the markdown for viewing the [tokens](https://github.com/mxenabled/mx-design-tokens/blob/master/docs/tokens.md)                |
| `npm run build:json` | Compile static JSON tokens for development                                  |
| `npm run build:scss` | Compile static SCSS files for projects using [Sass](https://sass-lang.com/) |
| `npm run build:css`  | Compile static CSS variables for use in any web project                     |
| `npm run build:all`  | Builds everything above in one easy step                                    |

The generated markdown documentation properly shows like this example...

## BackgroundColor

| Key | Value | Color |
| --- | ----- | ----- |
| ButtonDestructive | #DF320C | [#DF320C](https://www.colorhexa.com/DF320C) |
| ButtonDestructiveHover | #C61A0B | [#C61A0B](https://www.colorhexa.com/C61A0B) |
| ButtonPrimary | #2F73DA | [#2F73DA](https://www.colorhexa.com/2F73DA) |
| ButtonPrimaryHover | #165ECC | [#165ECC](https://www.colorhexa.com/165ECC) |

### CODE REVIEW

**Comment by jgerlach** [comment]
I see that you are generating `scss` and `css` files, but how would you go about importing them into your project?

**Comment by sambev** [comment]
@jgerlach
>I see that you are generating scss and css files, but how would you go about importing them into your project?

I am not sure we want to make that decision quite yet and maybe never, as it would probably change from project to project? That is my first thought at least.

Somewhat along those lines, I think I have missed some back story, but does anyone know why we are building and committing the json and css/scss? My first thought is that we wouldn't commit those and have the consumers build them themselves.

**Comment by jgerlach** [comment]
Dave is still looking into how we should actually import and use the `scss/css` files. I talked to him this morning and he told me to add the comment here so we could keep track of things.

**Comment by sambev** [comment]
@jgerlach @run-time what are some of the ideas you are exploring?

**Comment by ppkn** [comment]
As far as Rails is concerned, all we need is an `scss` file that we can drop into the stylesheets folder.

The only thing that doesn't get is versioning. You can only keep it up to date by replacing it with a new file.

**Comment by jgerlach** [comment]
It would be nice to show the values for both light and dark themes on the docs page. I'm not sure it's 100% necessary though since it's more useful for devs working on the actual components.

**Pull request merged**
